[package]
name = "vel_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
eframe = "0.16.0"
egui_node_graph = "0.2.0"

[profile.release]
opt-level = 2